#!/bin/bash
#include <stdio.h>
 
int main()
{
   char ch;
 
   printf("Enter any character\n");
   scanf("%c", &ch);
   if ( isalpha ( ch ) )
      printf ( "\nEntered character is alphabetic" ) ;
   else
      printf ( "\nEntered character is not alphabetic" ) ;
}
