#!/bin/bash
#include <stdio.h>
 
int main()
{
   char ch;
   printf("Enter any character\n");
   scanf("%c", &ch);
 
   if ( isupper ( ch ) )
      printf ("\nEntered character is uppercase character");
   else
      printf("\nEntered character is not uppercase character");
}
